---
driver:
  name: docker 

provisioner:
  name: chef_solo
  data_bags_path: ../../data_bags

platforms:
  - name: ubuntu-14.04
    driver_config:
      image: ubuntu:14.04
      platform: ubuntu
      forward:
      - 80:80

suites:
  - name: default
    run_list:
      - recipe[demo::default]
    attributes:
